version: 2
updates:
- package-ecosystem: gomod
  directory: "/"
  schedule:
    interval: daily
    time: "11:00"
  ignore:
  - dependency-name: k8s.io/apiextensions-apiserver
    versions:
    - 0.20.4
    - 0.20.5
  - dependency-name: github.com/onsi/gomega
    versions:
    - 1.10.5
  - dependency-name: k8s.io/api
    versions:
    - 0.20.2
    - 0.20.3
    - 0.20.4
  - dependency-name: github.com/pkg/errors
    versions:
    - 0.9.1
